### PR TITLE
Move to plugin.yml format

### PR DESCRIPTION
**Pull request by toolmantim**
This removes support for schema.yml and switches to a plugin.yml file, which must meet this JSON schema:

```yml
properties:
  name:
    type: string
    description: "Name of the plugin. For example: 'Shellcheck'"
  description:
    type: string
    description: "Description of what the plugin does. For example: 'Runs shellcheck on your shell scripts.'"
  author:
    type: string
    description: "Contact information for the author. For example: 'github.com/person'"
  requirements:
    type: array
    description: "Commands that are required to be present on the agent. For example: ['docker', 'docker-compose']"
  configuration:
    type: object
    description: "The JSON schema for the plugin’s configuration options. See http://json-schema.org and https://jsonschemalint.com/"
required:
  - name
  - description
  - author
  - requirements
  - configuration
```

For example:

```yml
name: junit-annotate
description: Annotates your build using JUnit XML reports
author: github.com/buildkite
requirements:
  - docker
configuration:
  properties:
    artifacts:
      type: string
    job-uuid-file-pattern:
      type: string
  required:
    - artifacts
  additionalProperties: false
```

### CODE REVIEW

**Comment by keithpitt** [comment]
Nice! Love it.

What about using `configuration` instead of the label `schema` to define the plugin config options?

**Comment by toolmantim** [comment]
I like `configuration` too! I suppose if we have good docs to tell you that it's in JSON schema format, then people will know to go look up "What the hell is JSON Schema"

**Comment by keithpitt** [comment]
Can we have this as the plugin schema?

```
properties:
  name:
    type: string
  description:
    type: string
  author:
    type: string
  requirements:
    type: array
  configuration:
    type: JSONSchema
required:
  - name
  - description
  - author
  - requirements
  - configuration
```

**Comment by toolmantim** [comment]
Ok, all renamed.

There's no `JSONSchema` type, but maybe we could use a reference:
https://cswr.github.io/JsonSchema/spec/definitions_references/

It's tricky, because over time the JSON schema spec changes, and you can switch which schema version you're using with the "$schema" key. So it's not fixed forever, and people can still use standard JSON linter tools. The node library we're using, `ajv`, supports different versions and is kept very up-to-date vs every Ruby gem etc which is out of date.

Maybe too hard for now?

**Comment by toolmantim** [comment]
(p.s. I imagine if we consumed this to generate a nice plugin directory, we'd use the same `ajv` JSON schema library)

**Comment by lox** [comment]
I find `configuration` really confusing. It's literally a schema, but as a user I'd assume that was where configuration went and scratch my head. 

My take is that it's better as a seperate file, because files that work with schemas generally expect that, as do people. Is there any prior art for a schema as a part of a configuration file?

**Comment by toolmantim** [comment]
Even tho I’m liking the change, I did just realize that I’ve been calling plugin.json/yml the “plugin config” file — which could make “configuration” confusing.

@lox It’s still quite copy+pastable into JSON Schema Lint and friends, they can handle the indent. It was a copy and paste job before too.

**Pull request merged**
